### PR TITLE
[wip] fix: adding inrastructure to build and release the project

### PR DESCRIPTION
**Pull request by hferentschik**
- restructured code and introdiced internal package
- updated Makefile
- added commit message validation
- added support for Skaffold

fix for issue #1

### CODE REVIEW

**Comment by hferentschik** [comment]
@wbrefvem, ok, seems we have not added this project yet to the Prow config of your prod cluster. Would be nice to get things at least kick started.

**Comment by hferentschik** [comment]
@wbrefvem, @abayer  - so after the latest discussion, does it make sense to get this project added to our prod cluster right now? Or shall we wait? 

I believe I have most pieces in place but would need to get the builds working in order to make final adjustments.

**Comment by wbrefvem** [comment]
@hferentschik Hmm.. it should be in the prod cluster. I added the repo to the prow config at https://github.com/jenkins-x/prow-config-tekton. @rawlingsj Any reason this wouldn't have been picked up automatically?

**Comment by hferentschik** [comment]
> Hmm.. it should be in the prod cluster. I added the repo to the prow config at https://github.com/jenkins-x/prow-config-tekton

not sure, might be worth double-checking everything and that all required bits, aka pre- and post-submit hooks are properly setup.

**Comment by abayer** [comment]
It needs the webhook set up - lemme do that.

**Comment by abayer** [comment]
well, that didn't do anything...

**Comment by wbrefvem** [comment]
> It needs the webhook set up - lemme do that.

Doh

**Comment by wbrefvem** [comment]
But in general, @hferentschik, lgtm

**Comment by hferentschik** [comment]
@abayer, btw does env inheritance work now in jenkins-x.yml? Could I define these env variables only once for all stages?

**Comment by wbrefvem** [comment]
@hferentschik looks like your latest run passed but we're still not getting status updates.

**Comment by hferentschik** [comment]
>  looks like your latest run passed but we're still not getting status updates.

I think @dgozalo had the same issue the other day. Build runs, but no updates on the pull request. Maybe he knows what's missing?

**Comment by abayer** [comment]
@hferentschik Env inheritance has _always_ worked. =)

**Comment by hferentschik** [comment]
>  Env inheritance has always worked. =)

Odd, I thought someone told me once it would not work and hence we keep duplicated all this env variables all the time.

**Comment by abayer** [comment]
Well, they were wrong! That literally has been there since day one, since that's how things work in Declarative, and I was deriving our behavior from that. =)

**Comment by hferentschik** [comment]
Closing for now.

**Comment by hferentschik** [comment]
> Well, they were wrong! That literally has been there since day one

I see. Looking for an example I found this - https://github.com/jenkins-x/jx/blob/283261f9c0a1bf29603517c3b9cc7ab5213ccea6/pkg/cmd/step/create/test_data/step_create_task/containerOptions-at-top-level-of-buildpack/jenkins-x.yml#L2

So on the _pipelineConfig_ level the key is _env_, but within stages it is _environment_? Is this intentional? That seems odd to me.

**Comment by abayer** [comment]
That was inadvertent, but `env` now works everywhere.

**Comment by hferentschik** [comment]
> That was inadvertent, but env now works everywhere.

Good to know. It might be worth doing a bit of a review and overhaul of the various config files we use across projects and clean them up a bit. Otherwise, things will just spread by cut&paste.

**Pull request closed without merging**
