### PR TITLE
fix: adding inrastructure to build and release the project

### PR DESCRIPTION
**Pull request by hferentschik**
- restructured code and introduced internal package
- updated Makefile
- added commit message validation
- added support for Skaffold

fix for issue #1

### CODE REVIEW

**Comment by hferentschik** [comment]
@wbrefvem, as you say, the jobs are actually triggered and succeed. I can see the logs and I can even see that the Prow pipeline controller "sees" the completion of it. I have no idea though why there is no status check visible though.

**Comment by abayer** [comment]
Permissions! I’ve added the relevant teams as collaborators. Should help.

**Comment by hferentschik** [comment]
> Permissions! I’ve added the relevant teams as collaborators. Should help.

LOL, that complicated ;-)

**Pull request merged**
